### ISSUE TITLE
HEEx roadmap

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#1506]
## Features v1

* [ ] Change all tests to use ~H/.heex
* [ ] Add components for live_patch/live_redirect (as well as button/link?)
* [ ] Validate HTML tree semantics (for example, you cannot have a form inside a tr)
* [ ] Validate HTML attributes: for example, validate the values of phx-* attributes and that certain phx-* attributes require an ID

## Deprecations

* [ ] Deprecate `~L` on stateful LiveComponent. This needs to be deprecated first because optimizations depend on it. We perhaps should also generate data-cid on the server.
* [ ] Deprecate stateless live component

## Features v2

Those features will come further down the road.

* [ ] API to declare the types of assigns on function components which can be statically verified. This has many open questions, such as how does it work on (if at all) on LiveView, on LiveComponent, etc.
* [ ] API for macro components?

**Comment by dustinfarris** [comment]
@josevalim @msaraiva Does it make sense to use Surface in the interim?  Will there be a migration path from Surface to HEEx?

**Comment by josevalim** [comment]
@dustinfarris afaik all of the features already exist on Surface and the goal is that both Surface and HEEx will use the same abstractions. So they will effectively be different syntaxes to the same abstractions.

**Comment by thiagomajesk** [comment]
@josevalim will HEEx and the component system be available outside of Live View? 

I started working on a similar library to have "View Components" inside Elixir sometime ago, but it still feels clunky:
https://github.com/thiagomajesk/viewplex. One of the great additions I saw in the [changelog](https://github.com/phoenixframework/phoenix_live_view/blob/master/CHANGELOG.md) was the custom engine that will allow for "Component Tags".
 
My inspiration was ASP.NET View Components and Laravel Blade Components which makes the developer's life a lot easier (especially if you are working with something like TailwindCSS).

Based on some projects I have worked on, I have reasons to believe that the component system would be a great addition to the default Phoenix engine (where views and templates are not enough).

**Comment by josevalim** [comment]
Yes, the new stuff works outside of LiveView.   Only stateful components require LiveView.

**Comment by jherdman** [comment]
Let's suppose you have a generic button component with some default styling. Using the above API I'd have to do this (as you explained):

```elixir
defp merge_button_classes(custom_classes \\ "") do
  "border-2 border-solid text-sm " <> custom_classes
end

assign :label, :string
assign :class, :string
assign :attributes, :rest
def button(assigns) do
  ~H"""
  <button
    type="button"
    class={merge_button_classes(@class)}
  >
    <%= @label %>
  </button>
  """
end
```

And invocation would look like this:

```elixir
<.button label="Hello, José!" class="border-indigo-700 bg-indigo-300" data-test-selector="my-button" />
```

To get this result:

```html
<button
  type="button"
  class="border-2 border-solid text-sm border-indigo-700 bg-indigo-300"
  data-test-selector="my-button"
>
  Hello, José!
</button>
```

This is OK, but 9/10 we _always_ want to merge class names if some are already assigned. I'd really like to be able to do this to achieve the same result.

```elixir
assign :label, :string
assign :attributes, :rest
def button(assigns) do
  ~H"""
  <button
    type="button"
    class="border-2 border-solid text-sm"
    {@attributes}
  >
    <%= @label %>
  </button>
  """
end
```

Another thought I just had regarding Ember's Glimmer component API is that you can assign DOM attributes _and_ arguments with the same name (not that this would necessarily be a good idea). A **very** contrived example that hopefully no one would ever do in real life:

```elixir
<.button
  type="button" <%# i want this as the attribute on my DOM node %>
  type="primary" <%# i want this to be an argument... uh oh! collision! %>
```

**Comment by josevalim** [comment]
Yes, you would have to explicitly merge them. Not ideal but I am sure we can find ways to improve it. For example, if we can give default values to assigns, then you could even do:

```elixir
assign :label, :string
assign :class, :string, default: ""
assign :attributes, :rest
def button(assigns) do
  assigns = update(assigns, :class, &["my-classes" | &1])

  ~H"""
  <button type="button" class={@class}>
    <%= @label %>
  </button>
  """
end
```

Note: we may need to support improper lists on classes, but it is definitely doable. Or we introduce a ":class" type that automatically normalizes them to lists.

My concern with allowing something like:

```elixir
  <button
    type="button"
    class="border-2 border-solid text-sm"
    {@attributes}
  >
```

Is that now whenever you see a splat attributes (`{...}`) we cannot send any of the other attributes as static, as they may be overridden. This is not a trade-off for Glimmer, because I assume it is all client side, but definitely something to consider here as static contents are sent once over the wire.

Regarding `@type=` vs `type=`, I need to think more about it and try to understand why other frameworks did not go for such approach. :)

**Comment by jherdman** [comment]
Yeah, sadly I cannot offer any insight into other frameworks. My experience is fully in Ember. Thank you for your time, consideration, and thoughtful responses.

**Comment by josevalim** [comment]
And thank you for the insights and the discussion! :heart:

**Comment by josevalim** [comment]
@jherdman related to this discussion, one idea we might want to investigate is how to make both classes "findable" by Tailwind. Perhaps we should support explicit merging like this:

```elixir
  <button
    type="button"
    prepend:class="border-2 border-solid text-sm"
    {@attributes}
  >
```

This way we get to know which classes need to be dynamically merged while keeping the overall remaining features.

**Comment by jherdman** [comment]
I thought of another edge case:

```elixir
def link_to_asset(assigns) do
  ~H"""
  <a
    href={@url}
    target="_blank"
  >
    <%= @url %>
  </a>
  """
end
```

Suppose in my invocation of this component that I want to override `target="_blank"`. Does the `{@attributes}` solution handle this?

**Comment by josevalim** [comment]
In this case you would use assign_new to set the default value.

**Comment by josevalim** [comment]
@salalo I know this feature is being tracked by @msaraiva but we haven't discussed it yet.

**Comment by henrik** [comment]
Not sure if this belongs here, but after I've converted a project to the `<My.Component.fun />` syntax, I found myself wishing the function name could be left off. I currently have things like `<MyWeb.NoUsernameComponent.render />` where the function name feels a bit crufty. But I guess it would increase ambiguity (is it a module or a tag name). Just feels like it would be a common thing to want to have one component per module. If nothing else, perhaps the docs could include (happy to PR) an example of a module with a generic method name like render/call/whatever, just to establish a convention for this presumed-common case?

**Comment by josevalim** [comment]
@henrik this is pretty much on purpose. We don't want developers to create a module per component, rather to group those components together into functions. So I would say having something like `MyWeb.NoUsernameComponent.render` is pretty much an anti-pattern for functional components. Docs have recently been updated to make this a bit more explicit.

**Comment by henrik** [comment]
Ah, thank you @josevalim! I see there is a `MyApp.Weather.city` [example](https://github.com/phoenixframework/phoenix_live_view/blob/9d95bfde0aee2e8184000d0d2319df05edd3c35e/lib/phoenix_live_view/helpers.ex#L51).

So in this case with small used-in-multiple-live-views components like [NoUsernameComponent](https://github.com/barsoom/ex-remit/blob/master/lib/remit_web/live/no_username_component.ex) and [NoContentComponent](https://github.com/barsoom/ex-remit/blob/master/lib/remit_web/live/no_content_component.ex), I guess the recommended way might be something like `MyWeb.SharedComponents.no_username` or ``MyWeb.User.no_username`.

**Comment by sbaildon** [comment]
You could maybe call your module `EmptyStates`, see https://emptystat.es

**Comment by henrik** [comment]
Out of curiosity (and if this is an OK forum for it), what is the thinking behind single-module components being an anti-pattern? Didn't find anything in the docs that seemed to explain it. Happy to make a PR to clarify if I come to understand it better. Single-module components seem reasonable to me – common in the React world, better cohesion if you extract private functions, can find easily by filename etc.

**Comment by josevalim** [comment]
Yeah, the docs don't go as far as calling it an anti-pattern but it mentions you should focus on multiple functions per module. The reason is that the building block of Elixir is functions, not modules. It is akin to why we have the `Enum` module with many functions instead of `Enum.Map.call` for each function instead.

**Comment by krainboltgreene** [comment]
I would love to work on this if possible. Are there any working groups or people already tackling these issues? If not are there any details on the listed issues?

**Comment by josevalim** [comment]
@krainboltgreene the two available tasks (validation and declarative assigns) are being tackled already. There is a PR for the later here (#1747). Then the only piece remaining is the catalogue but it requires declarative assigns. I will drop a note here once it is ready to tackle.

**Comment by connorlay** [comment]
@josevalim I am interested in contributing to a HEEx component catalogue for Live View. I wrote a proof-of-concept version at work for function and live components that our designers and engineers are using to iterate on our new design system 😄

Based on my experiments so far so far I have identified two offerings such a catalogue could provide:

1) a searchable index of all components that displays Elixir module & function documentation, metadata about declarative assigns (types, defaults, etc.), and examples rendered in the DOM that can be interacted with.

2) a sandbox for interactively creating and modifying components when running in development mode, including live reloading of code changes, controls to manipulate the client live socket (latency, disconnect/reconnect states, etc.), and a resizable iframe to easily test different viewport sizes.

I think such a tool would need to accommodate both software teams building applications with Phoenix Live View, as well as component library authors wanting to demonstrate what is available for use. What do you think?
