### ISSUE TITLE
Add change tracking to forms

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_live_view#2412]
1. [x] Implement Access protocol for `Form` that returns a `FormField` struct:
   `defstruct [:id, :name, :errors, :value, :field, :form]`

2. [x] Implement `Phoenix.LiveView.to_form` which converts a data structure to form

3. [x] Implement change tracking for access on `Form` by providing a `input_changed?(...)` API

4. [x] Implement `Phoenix.HTML.Form.normalize_value(type, value)` (are we good on name?)

5. [ ] Add `.errors` to `type="checkbox"` in core_components

6. [x] Update core_components to use the functionality above

7. [ ] Do a pass on documentation and guides to make sure all usage of `<.form` is
    without :let and using the new explicit `to_form` call

8. [ ] Add .inputs_for to LiveView depending on the context guides (see #2411)

9. [ ] Release phoenix_html 3.3.0

**Comment by thiagomajesk** [comment]
> 4\. Implement `Phoenix.HTML.Form.normalize_value(type, value)` (are we good on name?)

Other good options could be `format_value` (your previous suggestion) and `cast_value` if you want a shorter name 👍

**Comment by josevalim** [comment]
Just Phoenix HTML release missing now.
